name: hybridHiring
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - pandas
  - pip
  - openpyxl
  - pip:
      - openai
      - pebble
      - tqdm
      - warcio
      - backoff
